services:
  postgres-test:
    image: postgres:16-alpine
    container_name: flashcards-db-test
    environment:
      POSTGRES_USER: flashcards_test
      POSTGRES_PASSWORD: flashcards_test_password
      POSTGRES_DB: flashcards_test
    ports:
      - '5434:5432' # Другой порт, чтобы не конфликтовать с основной БД
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    networks:
      - flashcards-test-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U flashcards_test']
      interval: 2s
      timeout: 5s
      retries: 10

volumes:
  postgres_test_data:

networks:
  flashcards-test-network:
    driver: bridge
