-- Migration: words_to_fix
-- Generated: 2026-01-23 20:59:23
-- Words count: 10
-- Language: en
-- Strategy: UPSERT (insert or update existing, preserve existing IDs)

BEGIN;
SELECT pg_advisory_lock(hashtext('data_migrations_global_lock'));
SET LOCAL statement_timeout = '10min';
SET LOCAL lock_timeout = '60s';
SET LOCAL client_min_messages = warning;

-- Ensure languages exist (idempotent)
INSERT INTO "Language" ("code", "name") VALUES ('en', 'English'), ('ru', 'Russian'), ('es', 'Spanish')
ON CONFLICT ("code") DO NOTHING;

-- Ensure part of speech exists
INSERT INTO "PartOfSpeech" ("name") VALUES ('noun'), ('adjective'), ('adverb'), ('verb')
ON CONFLICT ("name") DO NOTHING;

-- Ensure word sources exist (including migration label)
INSERT INTO "WordSource" ("code", "displayName") VALUES ('native', 'Native'), ('dm_20260123205923_words_to_fix', 'Data Migration words_to_fix')
ON CONFLICT ("code") DO NOTHING;

-- UPSERT BaseWord records
-- New words get sourceId = dm_...; existing words keep their sourceId (so rollback does not delete them)
INSERT INTO "BaseWord" ("word", "languageId", "sourceId") VALUES
  ('approval', (SELECT "id" FROM "Language" WHERE "code" = 'en'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ('bioprinting', (SELECT "id" FROM "Language" WHERE "code" = 'en'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ('birdwatching', (SELECT "id" FROM "Language" WHERE "code" = 'en'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ('closet', (SELECT "id" FROM "Language" WHERE "code" = 'en'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ('coaching', (SELECT "id" FROM "Language" WHERE "code" = 'en'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ('cobbler', (SELECT "id" FROM "Language" WHERE "code" = 'en'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ('fashionable', (SELECT "id" FROM "Language" WHERE "code" = 'en'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ('reliably', (SELECT "id" FROM "Language" WHERE "code" = 'en'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ('impose', (SELECT "id" FROM "Language" WHERE "code" = 'en'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ('liesure', (SELECT "id" FROM "Language" WHERE "code" = 'en'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix'))
ON CONFLICT ("word", "languageId") DO NOTHING;

-- UPSERT WordTranslation records (subquery resolves baseWordId)
INSERT INTO "WordTranslation" ("baseWordId", "languageId", "translation", "priority", "partOfSpeechId") VALUES
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'approval' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Language" WHERE "code" = 'ru'), 'одобрение', 1, (SELECT "id" FROM "PartOfSpeech" WHERE "name" = 'noun')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'approval' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Language" WHERE "code" = 'ru'), 'утверждение', 2, (SELECT "id" FROM "PartOfSpeech" WHERE "name" = 'noun')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'approval' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Language" WHERE "code" = 'es'), 'aprobación', 1, (SELECT "id" FROM "PartOfSpeech" WHERE "name" = 'noun')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'approval' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Language" WHERE "code" = 'es'), 'autorización', 2, (SELECT "id" FROM "PartOfSpeech" WHERE "name" = 'noun')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'bioprinting' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Language" WHERE "code" = 'ru'), 'биопринтинг', 1, (SELECT "id" FROM "PartOfSpeech" WHERE "name" = 'noun')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'bioprinting' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Language" WHERE "code" = 'ru'), 'биопечать', 2, (SELECT "id" FROM "PartOfSpeech" WHERE "name" = 'noun')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'bioprinting' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Language" WHERE "code" = 'es'), 'bioprinting', 1, (SELECT "id" FROM "PartOfSpeech" WHERE "name" = 'noun')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'bioprinting' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Language" WHERE "code" = 'es'), 'bioimpresión', 2, (SELECT "id" FROM "PartOfSpeech" WHERE "name" = 'noun')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'birdwatching' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Language" WHERE "code" = 'ru'), 'наблюдение за птицами', 1, (SELECT "id" FROM "PartOfSpeech" WHERE "name" = 'noun')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'birdwatching' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Language" WHERE "code" = 'ru'), 'птицевание', 2, (SELECT "id" FROM "PartOfSpeech" WHERE "name" = 'noun')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'birdwatching' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Language" WHERE "code" = 'es'), 'observación de aves', 1, (SELECT "id" FROM "PartOfSpeech" WHERE "name" = 'noun')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'birdwatching' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Language" WHERE "code" = 'es'), 'avistamiento de pájaros', 2, (SELECT "id" FROM "PartOfSpeech" WHERE "name" = 'noun')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'closet' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Language" WHERE "code" = 'ru'), 'шкаф', 1, (SELECT "id" FROM "PartOfSpeech" WHERE "name" = 'noun')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'closet' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Language" WHERE "code" = 'ru'), 'гардероб', 2, (SELECT "id" FROM "PartOfSpeech" WHERE "name" = 'noun')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'closet' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Language" WHERE "code" = 'ru'), 'чулан', 3, (SELECT "id" FROM "PartOfSpeech" WHERE "name" = 'noun')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'closet' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Language" WHERE "code" = 'es'), 'armario', 1, (SELECT "id" FROM "PartOfSpeech" WHERE "name" = 'noun')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'closet' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Language" WHERE "code" = 'es'), 'clóset', 2, (SELECT "id" FROM "PartOfSpeech" WHERE "name" = 'noun')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'closet' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Language" WHERE "code" = 'es'), 'ropero', 3, (SELECT "id" FROM "PartOfSpeech" WHERE "name" = 'noun')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'coaching' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Language" WHERE "code" = 'ru'), 'коучинг', 1, (SELECT "id" FROM "PartOfSpeech" WHERE "name" = 'noun')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'coaching' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Language" WHERE "code" = 'ru'), 'тренерство', 2, (SELECT "id" FROM "PartOfSpeech" WHERE "name" = 'noun')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'coaching' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Language" WHERE "code" = 'ru'), 'обучение', 3, (SELECT "id" FROM "PartOfSpeech" WHERE "name" = 'noun')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'coaching' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Language" WHERE "code" = 'es'), 'coaching', 1, (SELECT "id" FROM "PartOfSpeech" WHERE "name" = 'noun')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'coaching' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Language" WHERE "code" = 'es'), 'entrenamiento', 2, (SELECT "id" FROM "PartOfSpeech" WHERE "name" = 'noun')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'coaching' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Language" WHERE "code" = 'es'), 'asesoramiento', 3, (SELECT "id" FROM "PartOfSpeech" WHERE "name" = 'noun')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'cobbler' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Language" WHERE "code" = 'ru'), 'сапожник', 1, (SELECT "id" FROM "PartOfSpeech" WHERE "name" = 'noun')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'cobbler' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Language" WHERE "code" = 'ru'), 'ремесленник', 2, (SELECT "id" FROM "PartOfSpeech" WHERE "name" = 'noun')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'cobbler' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Language" WHERE "code" = 'es'), 'zapatero', 1, (SELECT "id" FROM "PartOfSpeech" WHERE "name" = 'noun')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'cobbler' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Language" WHERE "code" = 'es'), 'artesano', 2, (SELECT "id" FROM "PartOfSpeech" WHERE "name" = 'noun')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'fashionable' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Language" WHERE "code" = 'ru'), 'модный', 1, (SELECT "id" FROM "PartOfSpeech" WHERE "name" = 'adjective')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'fashionable' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Language" WHERE "code" = 'ru'), 'стильный', 2, (SELECT "id" FROM "PartOfSpeech" WHERE "name" = 'adjective')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'fashionable' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Language" WHERE "code" = 'es'), 'de moda', 1, (SELECT "id" FROM "PartOfSpeech" WHERE "name" = 'adjective')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'fashionable' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Language" WHERE "code" = 'es'), 'a la moda', 2, (SELECT "id" FROM "PartOfSpeech" WHERE "name" = 'adjective')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'reliably' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Language" WHERE "code" = 'ru'), 'надежно', 1, (SELECT "id" FROM "PartOfSpeech" WHERE "name" = 'adverb')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'reliably' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Language" WHERE "code" = 'es'), 'de manera confiable', 1, (SELECT "id" FROM "PartOfSpeech" WHERE "name" = 'adverb')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'reliably' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Language" WHERE "code" = 'es'), 'fiablemente', 2, (SELECT "id" FROM "PartOfSpeech" WHERE "name" = 'adverb')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'impose' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Language" WHERE "code" = 'ru'), 'навязывать', 1, (SELECT "id" FROM "PartOfSpeech" WHERE "name" = 'verb')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'impose' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Language" WHERE "code" = 'ru'), 'налагать', 2, (SELECT "id" FROM "PartOfSpeech" WHERE "name" = 'verb')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'impose' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Language" WHERE "code" = 'es'), 'imponer', 1, (SELECT "id" FROM "PartOfSpeech" WHERE "name" = 'verb')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'liesure' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Language" WHERE "code" = 'ru'), 'досуг', 1, (SELECT "id" FROM "PartOfSpeech" WHERE "name" = 'noun')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'liesure' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Language" WHERE "code" = 'ru'), 'отдых', 2, (SELECT "id" FROM "PartOfSpeech" WHERE "name" = 'noun')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'liesure' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Language" WHERE "code" = 'ru'), 'свободное время', 3, (SELECT "id" FROM "PartOfSpeech" WHERE "name" = 'noun')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'liesure' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Language" WHERE "code" = 'es'), 'ocio', 1, (SELECT "id" FROM "PartOfSpeech" WHERE "name" = 'noun')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'liesure' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Language" WHERE "code" = 'es'), 'tiempo libre', 2, (SELECT "id" FROM "PartOfSpeech" WHERE "name" = 'noun')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'liesure' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Language" WHERE "code" = 'es'), 'recreo', 3, (SELECT "id" FROM "PartOfSpeech" WHERE "name" = 'noun'))
ON CONFLICT ("baseWordId", "languageId", "priority") DO UPDATE SET
  "translation" = EXCLUDED."translation",
  "partOfSpeechId" = EXCLUDED."partOfSpeechId";

-- Replace examples: delete old rows and insert new ones.
-- Tag new examples with sourceId = dm_... (for selective rollback deletion)
DELETE FROM "WordExample"
WHERE "baseWordId" IN (
  SELECT "id" FROM "BaseWord"
  WHERE "word" IN ('approval', 'bioprinting', 'birdwatching', 'closet', 'coaching', 'cobbler', 'fashionable', 'reliably', 'impose', 'liesure')
  AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')
);

-- Ensure sentence types exist
INSERT INTO "SentenceType" ("code", "displayName", "isNegative", "isQuestion") VALUES ('AFFIRMATIVE', 'affirmative', false, false)
ON CONFLICT ("code") DO NOTHING;
INSERT INTO "SentenceType" ("code", "displayName", "isNegative", "isQuestion") VALUES ('QUESTION', 'question', false, true)
ON CONFLICT ("code") DO NOTHING;
INSERT INTO "SentenceType" ("code", "displayName", "isNegative", "isQuestion") VALUES ('NEGATIVE', 'negative', true, false)
ON CONFLICT ("code") DO NOTHING;

INSERT INTO "WordExample" ("baseWordId", "pronounId", "example", "translation", "translationLanguageId", "sentenceTypeId", "sourceId") VALUES
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'approval' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'I' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'I need your approval for this plan', 'Мне нужно ваше одобрение на этот план', (SELECT "id" FROM "Language" WHERE "code" = 'ru'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'approval' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'I' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'I need your approval for this plan', 'Necesito tu aprobación para este plan', (SELECT "id" FROM "Language" WHERE "code" = 'es'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'approval' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'you' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'You have my full approval', 'У тебя есть мое полное одобрение', (SELECT "id" FROM "Language" WHERE "code" = 'ru'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'approval' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'you' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'You have my full approval', 'Tienes mi aprobación completa', (SELECT "id" FROM "Language" WHERE "code" = 'es'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'approval' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'he' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'Does he give his approval often?', 'Он часто дает свое одобрение?', (SELECT "id" FROM "Language" WHERE "code" = 'ru'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'QUESTION'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'approval' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'he' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'Does he give his approval often?', '¿Él da su aprobación a menudo?', (SELECT "id" FROM "Language" WHERE "code" = 'es'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'QUESTION'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'approval' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'we' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'We don''t have approval yet', 'У нас еще нет одобрения', (SELECT "id" FROM "Language" WHERE "code" = 'ru'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'NEGATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'approval' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'we' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'We don''t have approval yet', 'No tenemos aprobación todavía', (SELECT "id" FROM "Language" WHERE "code" = 'es'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'NEGATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'approval' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'they' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'They seek parental approval', 'Они ищут родительское одобрение', (SELECT "id" FROM "Language" WHERE "code" = 'ru'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'approval' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'they' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'They seek parental approval', 'Ellos buscan la aprobación de los padres', (SELECT "id" FROM "Language" WHERE "code" = 'es'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'bioprinting' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'I' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'I am learning about bioprinting', 'Я изучаю биопринтинг', (SELECT "id" FROM "Language" WHERE "code" = 'ru'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'bioprinting' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'I' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'I am learning about bioprinting', 'Estoy aprendiendo sobre bioprinting', (SELECT "id" FROM "Language" WHERE "code" = 'es'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'bioprinting' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'you' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'You know a lot about bioprinting', 'Ты знаешь много о биопринтинге', (SELECT "id" FROM "Language" WHERE "code" = 'ru'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'bioprinting' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'you' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'You know a lot about bioprinting', 'Sabes mucho sobre bioprinting', (SELECT "id" FROM "Language" WHERE "code" = 'es'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'bioprinting' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'he' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'Does he work in bioprinting?', 'Он работает в биопринтинге?', (SELECT "id" FROM "Language" WHERE "code" = 'ru'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'QUESTION'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'bioprinting' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'he' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'Does he work in bioprinting?', '¿Él trabaja en bioprinting?', (SELECT "id" FROM "Language" WHERE "code" = 'es'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'QUESTION'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'bioprinting' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'we' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'We don''t have bioprinting technology', 'У нас нет технологии биопринтинга', (SELECT "id" FROM "Language" WHERE "code" = 'ru'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'NEGATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'bioprinting' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'we' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'We don''t have bioprinting technology', 'No tenemos tecnología de bioprinting', (SELECT "id" FROM "Language" WHERE "code" = 'es'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'NEGATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'bioprinting' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'they' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'They are experts in bioprinting', 'Они эксперты в биопринтинге', (SELECT "id" FROM "Language" WHERE "code" = 'ru'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'bioprinting' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'they' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'They are experts in bioprinting', 'Ellos son expertos en bioprinting', (SELECT "id" FROM "Language" WHERE "code" = 'es'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'birdwatching' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'I' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'I enjoy birdwatching', 'Я люблю наблюдать за птицами', (SELECT "id" FROM "Language" WHERE "code" = 'ru'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'birdwatching' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'I' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'I enjoy birdwatching', 'Disfruto observando aves', (SELECT "id" FROM "Language" WHERE "code" = 'es'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'birdwatching' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'you' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'You started birdwatching last year', 'Ты начал наблюдать за птицами в прошлом году', (SELECT "id" FROM "Language" WHERE "code" = 'ru'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'birdwatching' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'you' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'You started birdwatching last year', 'Empezaste a observar aves el año pasado', (SELECT "id" FROM "Language" WHERE "code" = 'es'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'birdwatching' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'he' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'Does he like birdwatching?', 'Ему нравится наблюдать за птицами?', (SELECT "id" FROM "Language" WHERE "code" = 'ru'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'QUESTION'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'birdwatching' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'he' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'Does he like birdwatching?', '¿Le gusta observar aves?', (SELECT "id" FROM "Language" WHERE "code" = 'es'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'QUESTION'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'birdwatching' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'we' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'We don''t go birdwatching often', 'Мы не часто занимаемся наблюдением за птицами', (SELECT "id" FROM "Language" WHERE "code" = 'ru'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'NEGATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'birdwatching' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'we' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'We don''t go birdwatching often', 'No vamos a observar aves con frecuencia', (SELECT "id" FROM "Language" WHERE "code" = 'es'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'NEGATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'birdwatching' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'they' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'They have special equipment for birdwatching', 'У них есть специальное оборудование для наблюдения за птицами', (SELECT "id" FROM "Language" WHERE "code" = 'ru'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'birdwatching' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'they' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'They have special equipment for birdwatching', 'Tienen equipo especial para observar aves', (SELECT "id" FROM "Language" WHERE "code" = 'es'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'closet' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'I' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'I store my clothes in the closet', 'Я храню свою одежду в шкафу', (SELECT "id" FROM "Language" WHERE "code" = 'ru'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'closet' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'I' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'I store my clothes in the closet', 'Guardo mi ropa en el armario', (SELECT "id" FROM "Language" WHERE "code" = 'es'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'closet' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'you' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'You have a big closet', 'У тебя большой шкаф', (SELECT "id" FROM "Language" WHERE "code" = 'ru'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'closet' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'you' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'You have a big closet', 'Tienes un armario grande', (SELECT "id" FROM "Language" WHERE "code" = 'es'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'closet' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'he' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'Does he clean the closet?', 'Он убирает шкаф?', (SELECT "id" FROM "Language" WHERE "code" = 'ru'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'QUESTION'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'closet' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'he' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'Does he clean the closet?', '¿Él limpia el armario?', (SELECT "id" FROM "Language" WHERE "code" = 'es'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'QUESTION'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'closet' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'we' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'We don''t have a walk-in closet', 'У нас нет гардеробной', (SELECT "id" FROM "Language" WHERE "code" = 'ru'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'NEGATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'closet' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'we' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'We don''t have a walk-in closet', 'No tenemos un clóset walk-in', (SELECT "id" FROM "Language" WHERE "code" = 'es'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'NEGATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'closet' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'they' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'They organized the closet well', 'Они хорошо организовали шкаф', (SELECT "id" FROM "Language" WHERE "code" = 'ru'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'closet' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'they' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'They organized the closet well', 'Ellos organizaron bien el armario', (SELECT "id" FROM "Language" WHERE "code" = 'es'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'closet' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'she' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'She hides in the closet', 'Она прячется в шкафу', (SELECT "id" FROM "Language" WHERE "code" = 'ru'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'closet' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'she' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'She hides in the closet', 'Ella se esconde en el armario', (SELECT "id" FROM "Language" WHERE "code" = 'es'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'coaching' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'I' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'I enjoy coaching young athletes', 'Мне нравится тренировать молодых спортсменов', (SELECT "id" FROM "Language" WHERE "code" = 'ru'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'coaching' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'I' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'I enjoy coaching young athletes', 'Me gusta entrenar a jóvenes atletas', (SELECT "id" FROM "Language" WHERE "code" = 'es'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'coaching' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'you' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'You need coaching for this sport', 'Тебе нужно обучение для этого спорта', (SELECT "id" FROM "Language" WHERE "code" = 'ru'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'coaching' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'you' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'You need coaching for this sport', 'Necesitas entrenamiento para este deporte', (SELECT "id" FROM "Language" WHERE "code" = 'es'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'coaching' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'he' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'Does he provide coaching sessions?', 'Он проводит сессии коучинга?', (SELECT "id" FROM "Language" WHERE "code" = 'ru'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'QUESTION'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'coaching' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'he' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'Does he provide coaching sessions?', '¿Él proporciona sesiones de coaching?', (SELECT "id" FROM "Language" WHERE "code" = 'es'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'QUESTION'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'coaching' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'we' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'We don''t offer coaching here', 'Мы не предлагаем коучинг здесь', (SELECT "id" FROM "Language" WHERE "code" = 'ru'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'NEGATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'coaching' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'we' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'We don''t offer coaching here', 'No ofrecemos coaching aquí', (SELECT "id" FROM "Language" WHERE "code" = 'es'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'NEGATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'coaching' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'they' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'They excel in coaching teams', 'Они превосходны в тренерстве команд', (SELECT "id" FROM "Language" WHERE "code" = 'ru'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'coaching' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'they' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'They excel in coaching teams', 'Ellos sobresalen en el entrenamiento de equipos', (SELECT "id" FROM "Language" WHERE "code" = 'es'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'cobbler' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'I' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'I am a cobbler', 'Я сапожник', (SELECT "id" FROM "Language" WHERE "code" = 'ru'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'cobbler' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'I' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'I am a cobbler', 'Soy zapatero', (SELECT "id" FROM "Language" WHERE "code" = 'es'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'cobbler' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'you' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'Are you a cobbler?', 'Ты сапожник?', (SELECT "id" FROM "Language" WHERE "code" = 'ru'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'QUESTION'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'cobbler' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'you' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'Are you a cobbler?', '¿Eres zapatero?', (SELECT "id" FROM "Language" WHERE "code" = 'es'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'QUESTION'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'cobbler' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'he' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'He is not a cobbler', 'Он не сапожник', (SELECT "id" FROM "Language" WHERE "code" = 'ru'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'NEGATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'cobbler' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'he' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'He is not a cobbler', 'Él no es zapatero', (SELECT "id" FROM "Language" WHERE "code" = 'es'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'NEGATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'cobbler' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'we' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'We need a cobbler', 'Нам нужен сапожник', (SELECT "id" FROM "Language" WHERE "code" = 'ru'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'cobbler' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'we' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'We need a cobbler', 'Necesitamos un zapatero', (SELECT "id" FROM "Language" WHERE "code" = 'es'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'cobbler' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'they' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'They make cobblers', 'Они делают коблеры', (SELECT "id" FROM "Language" WHERE "code" = 'ru'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'cobbler' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'they' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'They make cobblers', 'Ellos hacen cobblers', (SELECT "id" FROM "Language" WHERE "code" = 'es'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'fashionable' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'I' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'I wear fashionable clothes', 'Я ношу модную одежду', (SELECT "id" FROM "Language" WHERE "code" = 'ru'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'fashionable' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'I' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'I wear fashionable clothes', 'Yo visto ropa de moda', (SELECT "id" FROM "Language" WHERE "code" = 'es'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'fashionable' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'you' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'You look very fashionable today', 'Ты выглядишь очень модно сегодня', (SELECT "id" FROM "Language" WHERE "code" = 'ru'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'fashionable' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'you' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'You look very fashionable today', 'Tú te ves muy a la moda hoy', (SELECT "id" FROM "Language" WHERE "code" = 'es'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'fashionable' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'he' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'Is he fashionable?', 'Он модный?', (SELECT "id" FROM "Language" WHERE "code" = 'ru'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'QUESTION'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'fashionable' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'he' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'Is he fashionable?', '¿Él es de moda?', (SELECT "id" FROM "Language" WHERE "code" = 'es'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'QUESTION'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'fashionable' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'we' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'We don''t have fashionable shoes', 'У нас нет модных туфель', (SELECT "id" FROM "Language" WHERE "code" = 'ru'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'NEGATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'fashionable' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'we' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'We don''t have fashionable shoes', 'Nosotros no tenemos zapatos de moda', (SELECT "id" FROM "Language" WHERE "code" = 'es'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'NEGATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'fashionable' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'they' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'They buy fashionable accessories', 'Они покупают модные аксессуары', (SELECT "id" FROM "Language" WHERE "code" = 'ru'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'fashionable' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'they' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'They buy fashionable accessories', 'Ellos compran accesorios de moda', (SELECT "id" FROM "Language" WHERE "code" = 'es'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'fashionable' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'she' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'She isn''t fashionable anymore', 'Она больше не модная', (SELECT "id" FROM "Language" WHERE "code" = 'ru'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'NEGATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'fashionable' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'she' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'She isn''t fashionable anymore', 'Ella ya no es de moda', (SELECT "id" FROM "Language" WHERE "code" = 'es'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'NEGATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'reliably' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'I' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'I work reliably', 'Я работаю надежно', (SELECT "id" FROM "Language" WHERE "code" = 'ru'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'reliably' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'I' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'I work reliably', 'Yo trabajo de manera confiable', (SELECT "id" FROM "Language" WHERE "code" = 'es'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'reliably' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'you' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'You perform reliably', 'Ты выступаешь надежно', (SELECT "id" FROM "Language" WHERE "code" = 'ru'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'reliably' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'you' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'You perform reliably', 'Tú actúas de manera confiable', (SELECT "id" FROM "Language" WHERE "code" = 'es'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'reliably' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'he' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'Does he work reliably?', 'Он работает надежно?', (SELECT "id" FROM "Language" WHERE "code" = 'ru'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'QUESTION'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'reliably' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'he' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'Does he work reliably?', '¿Él trabaja de manera confiable?', (SELECT "id" FROM "Language" WHERE "code" = 'es'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'QUESTION'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'reliably' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'we' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'We don''t deliver reliably', 'Мы не доставляем надежно', (SELECT "id" FROM "Language" WHERE "code" = 'ru'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'NEGATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'reliably' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'we' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'We don''t deliver reliably', 'Nosotros no entregamos de manera confiable', (SELECT "id" FROM "Language" WHERE "code" = 'es'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'NEGATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'reliably' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'they' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'They operate reliably', 'Они работают надежно', (SELECT "id" FROM "Language" WHERE "code" = 'ru'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'reliably' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'they' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'They operate reliably', 'Ellos operan de manera confiable', (SELECT "id" FROM "Language" WHERE "code" = 'es'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'impose' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'I' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'I impose my rules', 'Я навязываю свои правила', (SELECT "id" FROM "Language" WHERE "code" = 'ru'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'impose' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'I' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'I impose my rules', 'Yo impongo mis reglas', (SELECT "id" FROM "Language" WHERE "code" = 'es'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'impose' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'you' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'You impose too much', 'Ты навязываешь слишком много', (SELECT "id" FROM "Language" WHERE "code" = 'ru'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'impose' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'you' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'You impose too much', 'Tú impones demasiado', (SELECT "id" FROM "Language" WHERE "code" = 'es'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'impose' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'he' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'Does he impose his will?', 'Он навязывает свою волю?', (SELECT "id" FROM "Language" WHERE "code" = 'ru'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'QUESTION'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'impose' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'he' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'Does he impose his will?', '¿Él impone su voluntad?', (SELECT "id" FROM "Language" WHERE "code" = 'es'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'QUESTION'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'impose' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'we' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'We don''t impose sanctions', 'Мы не налагаем санкции', (SELECT "id" FROM "Language" WHERE "code" = 'ru'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'NEGATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'impose' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'we' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'We don''t impose sanctions', 'Nosotros no imponemos sanciones', (SELECT "id" FROM "Language" WHERE "code" = 'es'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'NEGATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'impose' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'they' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'They impose strict rules', 'Они налагают строгие правила', (SELECT "id" FROM "Language" WHERE "code" = 'ru'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'impose' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'they' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'They impose strict rules', 'Ellos imponen reglas estrictas', (SELECT "id" FROM "Language" WHERE "code" = 'es'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'impose' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'she' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'She imposes her opinion', 'Она навязывает свое мнение', (SELECT "id" FROM "Language" WHERE "code" = 'ru'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'impose' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'she' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'She imposes her opinion', 'Ella impone su opinión', (SELECT "id" FROM "Language" WHERE "code" = 'es'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'liesure' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'I' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'I enjoy my leisure time', 'Я наслаждаюсь своим свободным временем', (SELECT "id" FROM "Language" WHERE "code" = 'ru'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'liesure' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'I' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'I enjoy my leisure time', 'Disfruto de mi tiempo libre', (SELECT "id" FROM "Language" WHERE "code" = 'es'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'liesure' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'you' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'Your leisure activities are fun', 'Твои занятия досугом веселые', (SELECT "id" FROM "Language" WHERE "code" = 'ru'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'liesure' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'you' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'Your leisure activities are fun', 'Tus actividades de ocio son divertidas', (SELECT "id" FROM "Language" WHERE "code" = 'es'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'liesure' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'he' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'Does he have leisure time?', 'У него есть свободное время?', (SELECT "id" FROM "Language" WHERE "code" = 'ru'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'QUESTION'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'liesure' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'he' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'Does he have leisure time?', '¿Tiene él tiempo libre?', (SELECT "id" FROM "Language" WHERE "code" = 'es'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'QUESTION'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'liesure' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'we' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'We don''t have much leisure', 'У нас нет много досуга', (SELECT "id" FROM "Language" WHERE "code" = 'ru'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'NEGATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'liesure' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'we' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'We don''t have much leisure', 'No tenemos mucho ocio', (SELECT "id" FROM "Language" WHERE "code" = 'es'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'NEGATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'liesure' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'they' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'They spend leisure reading', 'Они проводят досуг за чтением', (SELECT "id" FROM "Language" WHERE "code" = 'ru'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'liesure' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'they' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'They spend leisure reading', 'Ellos pasan el ocio leyendo', (SELECT "id" FROM "Language" WHERE "code" = 'es'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix'))
ON CONFLICT DO NOTHING;

DELETE FROM "GrammaticalExample"
WHERE "baseWordId" IN (
  SELECT "id" FROM "BaseWord"
  WHERE "word" IN ('approval', 'bioprinting', 'birdwatching', 'closet', 'coaching', 'cobbler', 'fashionable', 'reliably', 'impose', 'liesure')
  AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')
);

-- Ensure tenses exist
INSERT INTO "Tense" ("name", "languageId") VALUES ('Present Simple', (SELECT "id" FROM "Language" WHERE "code" = 'en'))
ON CONFLICT ("name", "languageId") DO NOTHING;
INSERT INTO "Tense" ("name", "languageId") VALUES ('Past Simple', (SELECT "id" FROM "Language" WHERE "code" = 'en'))
ON CONFLICT ("name", "languageId") DO NOTHING;
INSERT INTO "Tense" ("name", "languageId") VALUES ('Future Simple', (SELECT "id" FROM "Language" WHERE "code" = 'en'))
ON CONFLICT ("name", "languageId") DO NOTHING;

-- Ensure pronouns exist
INSERT INTO "Pronoun" ("pronoun", "languageId") VALUES ('I', (SELECT "id" FROM "Language" WHERE "code" = 'en'))
ON CONFLICT ("pronoun", "languageId") DO NOTHING;
INSERT INTO "Pronoun" ("pronoun", "languageId") VALUES ('I', (SELECT "id" FROM "Language" WHERE "code" = 'en'))
ON CONFLICT ("pronoun", "languageId") DO NOTHING;
INSERT INTO "Pronoun" ("pronoun", "languageId") VALUES ('you', (SELECT "id" FROM "Language" WHERE "code" = 'en'))
ON CONFLICT ("pronoun", "languageId") DO NOTHING;
INSERT INTO "Pronoun" ("pronoun", "languageId") VALUES ('you', (SELECT "id" FROM "Language" WHERE "code" = 'en'))
ON CONFLICT ("pronoun", "languageId") DO NOTHING;
INSERT INTO "Pronoun" ("pronoun", "languageId") VALUES ('he', (SELECT "id" FROM "Language" WHERE "code" = 'en'))
ON CONFLICT ("pronoun", "languageId") DO NOTHING;
INSERT INTO "Pronoun" ("pronoun", "languageId") VALUES ('he', (SELECT "id" FROM "Language" WHERE "code" = 'en'))
ON CONFLICT ("pronoun", "languageId") DO NOTHING;
INSERT INTO "Pronoun" ("pronoun", "languageId") VALUES ('we', (SELECT "id" FROM "Language" WHERE "code" = 'en'))
ON CONFLICT ("pronoun", "languageId") DO NOTHING;
INSERT INTO "Pronoun" ("pronoun", "languageId") VALUES ('we', (SELECT "id" FROM "Language" WHERE "code" = 'en'))
ON CONFLICT ("pronoun", "languageId") DO NOTHING;
INSERT INTO "Pronoun" ("pronoun", "languageId") VALUES ('you', (SELECT "id" FROM "Language" WHERE "code" = 'en'))
ON CONFLICT ("pronoun", "languageId") DO NOTHING;
INSERT INTO "Pronoun" ("pronoun", "languageId") VALUES ('you', (SELECT "id" FROM "Language" WHERE "code" = 'en'))
ON CONFLICT ("pronoun", "languageId") DO NOTHING;
INSERT INTO "Pronoun" ("pronoun", "languageId") VALUES ('they', (SELECT "id" FROM "Language" WHERE "code" = 'en'))
ON CONFLICT ("pronoun", "languageId") DO NOTHING;
INSERT INTO "Pronoun" ("pronoun", "languageId") VALUES ('they', (SELECT "id" FROM "Language" WHERE "code" = 'en'))
ON CONFLICT ("pronoun", "languageId") DO NOTHING;
INSERT INTO "Pronoun" ("pronoun", "languageId") VALUES ('I', (SELECT "id" FROM "Language" WHERE "code" = 'en'))
ON CONFLICT ("pronoun", "languageId") DO NOTHING;
INSERT INTO "Pronoun" ("pronoun", "languageId") VALUES ('I', (SELECT "id" FROM "Language" WHERE "code" = 'en'))
ON CONFLICT ("pronoun", "languageId") DO NOTHING;
INSERT INTO "Pronoun" ("pronoun", "languageId") VALUES ('you', (SELECT "id" FROM "Language" WHERE "code" = 'en'))
ON CONFLICT ("pronoun", "languageId") DO NOTHING;
INSERT INTO "Pronoun" ("pronoun", "languageId") VALUES ('you', (SELECT "id" FROM "Language" WHERE "code" = 'en'))
ON CONFLICT ("pronoun", "languageId") DO NOTHING;
INSERT INTO "Pronoun" ("pronoun", "languageId") VALUES ('he', (SELECT "id" FROM "Language" WHERE "code" = 'en'))
ON CONFLICT ("pronoun", "languageId") DO NOTHING;
INSERT INTO "Pronoun" ("pronoun", "languageId") VALUES ('he', (SELECT "id" FROM "Language" WHERE "code" = 'en'))
ON CONFLICT ("pronoun", "languageId") DO NOTHING;
INSERT INTO "Pronoun" ("pronoun", "languageId") VALUES ('we', (SELECT "id" FROM "Language" WHERE "code" = 'en'))
ON CONFLICT ("pronoun", "languageId") DO NOTHING;
INSERT INTO "Pronoun" ("pronoun", "languageId") VALUES ('we', (SELECT "id" FROM "Language" WHERE "code" = 'en'))
ON CONFLICT ("pronoun", "languageId") DO NOTHING;
INSERT INTO "Pronoun" ("pronoun", "languageId") VALUES ('you', (SELECT "id" FROM "Language" WHERE "code" = 'en'))
ON CONFLICT ("pronoun", "languageId") DO NOTHING;
INSERT INTO "Pronoun" ("pronoun", "languageId") VALUES ('you', (SELECT "id" FROM "Language" WHERE "code" = 'en'))
ON CONFLICT ("pronoun", "languageId") DO NOTHING;
INSERT INTO "Pronoun" ("pronoun", "languageId") VALUES ('they', (SELECT "id" FROM "Language" WHERE "code" = 'en'))
ON CONFLICT ("pronoun", "languageId") DO NOTHING;
INSERT INTO "Pronoun" ("pronoun", "languageId") VALUES ('they', (SELECT "id" FROM "Language" WHERE "code" = 'en'))
ON CONFLICT ("pronoun", "languageId") DO NOTHING;
INSERT INTO "Pronoun" ("pronoun", "languageId") VALUES ('I', (SELECT "id" FROM "Language" WHERE "code" = 'en'))
ON CONFLICT ("pronoun", "languageId") DO NOTHING;
INSERT INTO "Pronoun" ("pronoun", "languageId") VALUES ('I', (SELECT "id" FROM "Language" WHERE "code" = 'en'))
ON CONFLICT ("pronoun", "languageId") DO NOTHING;
INSERT INTO "Pronoun" ("pronoun", "languageId") VALUES ('you', (SELECT "id" FROM "Language" WHERE "code" = 'en'))
ON CONFLICT ("pronoun", "languageId") DO NOTHING;
INSERT INTO "Pronoun" ("pronoun", "languageId") VALUES ('you', (SELECT "id" FROM "Language" WHERE "code" = 'en'))
ON CONFLICT ("pronoun", "languageId") DO NOTHING;
INSERT INTO "Pronoun" ("pronoun", "languageId") VALUES ('he', (SELECT "id" FROM "Language" WHERE "code" = 'en'))
ON CONFLICT ("pronoun", "languageId") DO NOTHING;
INSERT INTO "Pronoun" ("pronoun", "languageId") VALUES ('he', (SELECT "id" FROM "Language" WHERE "code" = 'en'))
ON CONFLICT ("pronoun", "languageId") DO NOTHING;
INSERT INTO "Pronoun" ("pronoun", "languageId") VALUES ('we', (SELECT "id" FROM "Language" WHERE "code" = 'en'))
ON CONFLICT ("pronoun", "languageId") DO NOTHING;
INSERT INTO "Pronoun" ("pronoun", "languageId") VALUES ('we', (SELECT "id" FROM "Language" WHERE "code" = 'en'))
ON CONFLICT ("pronoun", "languageId") DO NOTHING;
INSERT INTO "Pronoun" ("pronoun", "languageId") VALUES ('you', (SELECT "id" FROM "Language" WHERE "code" = 'en'))
ON CONFLICT ("pronoun", "languageId") DO NOTHING;
INSERT INTO "Pronoun" ("pronoun", "languageId") VALUES ('you', (SELECT "id" FROM "Language" WHERE "code" = 'en'))
ON CONFLICT ("pronoun", "languageId") DO NOTHING;
INSERT INTO "Pronoun" ("pronoun", "languageId") VALUES ('they', (SELECT "id" FROM "Language" WHERE "code" = 'en'))
ON CONFLICT ("pronoun", "languageId") DO NOTHING;
INSERT INTO "Pronoun" ("pronoun", "languageId") VALUES ('they', (SELECT "id" FROM "Language" WHERE "code" = 'en'))
ON CONFLICT ("pronoun", "languageId") DO NOTHING;

INSERT INTO "GrammaticalExample" ("baseWordId", "tenseId", "pronounId", "example", "translation", "translationLanguageId", "sentenceTypeId", "sourceId") VALUES
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'impose' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Tense" WHERE "name" = 'Present Simple' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'I' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'I impose', 'Я навязываю', (SELECT "id" FROM "Language" WHERE "code" = 'ru'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'impose' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Tense" WHERE "name" = 'Present Simple' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'I' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'I impose', 'Yo impongo', (SELECT "id" FROM "Language" WHERE "code" = 'es'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'impose' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Tense" WHERE "name" = 'Present Simple' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'you' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'You impose', 'Ты навязываешь', (SELECT "id" FROM "Language" WHERE "code" = 'ru'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'impose' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Tense" WHERE "name" = 'Present Simple' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'you' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'You impose', 'Tú impones', (SELECT "id" FROM "Language" WHERE "code" = 'es'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'impose' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Tense" WHERE "name" = 'Present Simple' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'he' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'He imposes', 'Он навязывает', (SELECT "id" FROM "Language" WHERE "code" = 'ru'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'impose' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Tense" WHERE "name" = 'Present Simple' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'he' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'He imposes', 'Él impone', (SELECT "id" FROM "Language" WHERE "code" = 'es'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'impose' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Tense" WHERE "name" = 'Present Simple' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'we' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'We impose', 'Мы навязываем', (SELECT "id" FROM "Language" WHERE "code" = 'ru'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'impose' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Tense" WHERE "name" = 'Present Simple' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'we' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'We impose', 'Nosotros imponemos', (SELECT "id" FROM "Language" WHERE "code" = 'es'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'impose' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Tense" WHERE "name" = 'Present Simple' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'you' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'You don''t impose', 'Вы не навязываете', (SELECT "id" FROM "Language" WHERE "code" = 'ru'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'NEGATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'impose' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Tense" WHERE "name" = 'Present Simple' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'you' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'You don''t impose', 'Vosotros no imponéis', (SELECT "id" FROM "Language" WHERE "code" = 'es'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'NEGATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'impose' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Tense" WHERE "name" = 'Present Simple' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'they' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'Do they impose?', 'Они навязывают?', (SELECT "id" FROM "Language" WHERE "code" = 'ru'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'QUESTION'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'impose' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Tense" WHERE "name" = 'Present Simple' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'they' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'Do they impose?', '¿Ellos imponen?', (SELECT "id" FROM "Language" WHERE "code" = 'es'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'QUESTION'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'impose' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Tense" WHERE "name" = 'Past Simple' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'I' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'I imposed', 'Я навязал', (SELECT "id" FROM "Language" WHERE "code" = 'ru'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'impose' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Tense" WHERE "name" = 'Past Simple' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'I' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'I imposed', 'Yo impuse', (SELECT "id" FROM "Language" WHERE "code" = 'es'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'impose' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Tense" WHERE "name" = 'Past Simple' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'you' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'You imposed', 'Ты навязал', (SELECT "id" FROM "Language" WHERE "code" = 'ru'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'impose' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Tense" WHERE "name" = 'Past Simple' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'you' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'You imposed', 'Tú impusiste', (SELECT "id" FROM "Language" WHERE "code" = 'es'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'impose' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Tense" WHERE "name" = 'Past Simple' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'he' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'He imposed', 'Он навязал', (SELECT "id" FROM "Language" WHERE "code" = 'ru'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'impose' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Tense" WHERE "name" = 'Past Simple' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'he' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'He imposed', 'Él impuso', (SELECT "id" FROM "Language" WHERE "code" = 'es'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'impose' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Tense" WHERE "name" = 'Past Simple' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'we' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'We imposed', 'Мы навязали', (SELECT "id" FROM "Language" WHERE "code" = 'ru'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'impose' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Tense" WHERE "name" = 'Past Simple' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'we' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'We imposed', 'Nosotros impusimos', (SELECT "id" FROM "Language" WHERE "code" = 'es'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'impose' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Tense" WHERE "name" = 'Past Simple' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'you' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'You didn''t impose', 'Вы не навязали', (SELECT "id" FROM "Language" WHERE "code" = 'ru'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'NEGATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'impose' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Tense" WHERE "name" = 'Past Simple' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'you' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'You didn''t impose', 'Vosotros no impusisteis', (SELECT "id" FROM "Language" WHERE "code" = 'es'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'NEGATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'impose' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Tense" WHERE "name" = 'Past Simple' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'they' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'Did they impose?', 'Они навязали?', (SELECT "id" FROM "Language" WHERE "code" = 'ru'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'QUESTION'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'impose' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Tense" WHERE "name" = 'Past Simple' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'they' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'Did they impose?', '¿Ellos impusieron?', (SELECT "id" FROM "Language" WHERE "code" = 'es'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'QUESTION'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'impose' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Tense" WHERE "name" = 'Future Simple' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'I' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'I will impose', 'Я буду навязывать', (SELECT "id" FROM "Language" WHERE "code" = 'ru'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'impose' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Tense" WHERE "name" = 'Future Simple' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'I' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'I will impose', 'Yo impondré', (SELECT "id" FROM "Language" WHERE "code" = 'es'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'impose' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Tense" WHERE "name" = 'Future Simple' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'you' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'You will impose', 'Ты будешь навязывать', (SELECT "id" FROM "Language" WHERE "code" = 'ru'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'impose' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Tense" WHERE "name" = 'Future Simple' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'you' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'You will impose', 'Tú impondrás', (SELECT "id" FROM "Language" WHERE "code" = 'es'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'impose' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Tense" WHERE "name" = 'Future Simple' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'he' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'He will impose', 'Он будет навязывать', (SELECT "id" FROM "Language" WHERE "code" = 'ru'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'impose' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Tense" WHERE "name" = 'Future Simple' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'he' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'He will impose', 'Él impondrá', (SELECT "id" FROM "Language" WHERE "code" = 'es'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'impose' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Tense" WHERE "name" = 'Future Simple' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'we' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'We will impose', 'Мы будем навязывать', (SELECT "id" FROM "Language" WHERE "code" = 'ru'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'impose' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Tense" WHERE "name" = 'Future Simple' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'we' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'We will impose', 'Nosotros impondremos', (SELECT "id" FROM "Language" WHERE "code" = 'es'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'impose' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Tense" WHERE "name" = 'Future Simple' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'you' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'You won''t impose', 'Вы не будете навязывать', (SELECT "id" FROM "Language" WHERE "code" = 'ru'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'NEGATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'impose' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Tense" WHERE "name" = 'Future Simple' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'you' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'You won''t impose', 'Vosotros no impondréis', (SELECT "id" FROM "Language" WHERE "code" = 'es'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'NEGATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'impose' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Tense" WHERE "name" = 'Future Simple' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'they' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'Will they impose?', 'Они будут навязывать?', (SELECT "id" FROM "Language" WHERE "code" = 'ru'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'QUESTION'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'impose' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Tense" WHERE "name" = 'Future Simple' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'they' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'Will they impose?', '¿Ellos impondrán?', (SELECT "id" FROM "Language" WHERE "code" = 'es'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'QUESTION'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260123205923_words_to_fix'))
ON CONFLICT DO NOTHING;

-- Apply script records migration metadata (time, checksum, gitSha) after successful execution

SELECT pg_advisory_unlock(hashtext('data_migrations_global_lock'));
COMMIT;