-- Migration: deepl_en
-- Generated: 2026-07-29 17:02:00
-- Words count: 3
-- Language: en
-- Strategy: UPSERT (insert or update existing, preserve existing IDs)

BEGIN;
SELECT pg_advisory_lock(hashtext('data_migrations_global_lock'));
SET LOCAL statement_timeout = '10min';
SET LOCAL lock_timeout = '60s';
SET LOCAL client_min_messages = warning;

-- Ensure languages exist (idempotent)
INSERT INTO "Language" ("code", "name") VALUES ('en', 'English'), ('ru', 'Russian'), ('es', 'Spanish')
ON CONFLICT ("code") DO NOTHING;

-- Ensure part of speech exists
INSERT INTO "PartOfSpeech" ("name") VALUES ('verb'), ('noun')
ON CONFLICT ("name") DO NOTHING;

-- Ensure word sources exist (including migration label)
INSERT INTO "WordSource" ("code", "displayName") VALUES ('native', 'Native'), ('dm_20260729170032_deepl_en', 'Data Migration deepl_en')
ON CONFLICT ("code") DO NOTHING;

-- UPSERT BaseWord records
-- Новые слова получают sourceId = dm_...; существующие слова не меняют sourceId (чтобы rollback не удалил их)
INSERT INTO "BaseWord" ("word", "languageId", "sourceId") VALUES
  ('accusing', (SELECT "id" FROM "Language" WHERE "code" = 'en'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260729170032_deepl_en')),
  ('authenticity', (SELECT "id" FROM "Language" WHERE "code" = 'en'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260729170032_deepl_en')),
  ('backpressure', (SELECT "id" FROM "Language" WHERE "code" = 'en'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260729170032_deepl_en'))
ON CONFLICT ("word", "languageId") DO NOTHING;

-- UPSERT WordTranslation records (используем подзапрос для получения baseWordId)
INSERT INTO "WordTranslation" ("baseWordId", "languageId", "translation", "priority", "partOfSpeechId") VALUES
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'accusing' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Language" WHERE "code" = 'ru'), 'обвинять', 1, (SELECT "id" FROM "PartOfSpeech" WHERE "name" = 'verb')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'accusing' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Language" WHERE "code" = 'ru'), 'винить', 2, (SELECT "id" FROM "PartOfSpeech" WHERE "name" = 'verb')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'accusing' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Language" WHERE "code" = 'ru'), 'инкриминировать', 3, (SELECT "id" FROM "PartOfSpeech" WHERE "name" = 'verb')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'accusing' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Language" WHERE "code" = 'es'), 'acusar', 1, (SELECT "id" FROM "PartOfSpeech" WHERE "name" = 'verb')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'accusing' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Language" WHERE "code" = 'es'), 'culpar', 2, (SELECT "id" FROM "PartOfSpeech" WHERE "name" = 'verb')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'accusing' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Language" WHERE "code" = 'es'), 'incriminar', 3, (SELECT "id" FROM "PartOfSpeech" WHERE "name" = 'verb')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'authenticity' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Language" WHERE "code" = 'ru'), 'аутентичность', 1, (SELECT "id" FROM "PartOfSpeech" WHERE "name" = 'noun')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'authenticity' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Language" WHERE "code" = 'ru'), 'подлинность', 2, (SELECT "id" FROM "PartOfSpeech" WHERE "name" = 'noun')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'authenticity' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Language" WHERE "code" = 'ru'), 'достоверность', 3, (SELECT "id" FROM "PartOfSpeech" WHERE "name" = 'noun')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'authenticity' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Language" WHERE "code" = 'es'), 'autenticidad', 1, (SELECT "id" FROM "PartOfSpeech" WHERE "name" = 'noun')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'authenticity' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Language" WHERE "code" = 'es'), 'autentidad', 2, (SELECT "id" FROM "PartOfSpeech" WHERE "name" = 'noun')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'backpressure' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Language" WHERE "code" = 'ru'), 'обратное давление', 1, (SELECT "id" FROM "PartOfSpeech" WHERE "name" = 'noun')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'backpressure' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Language" WHERE "code" = 'ru'), 'противодавление', 2, (SELECT "id" FROM "PartOfSpeech" WHERE "name" = 'noun')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'backpressure' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Language" WHERE "code" = 'es'), 'contrapresión', 1, (SELECT "id" FROM "PartOfSpeech" WHERE "name" = 'noun')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'backpressure' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Language" WHERE "code" = 'es'), 'presión de retorno', 2, (SELECT "id" FROM "PartOfSpeech" WHERE "name" = 'noun'))
ON CONFLICT ("baseWordId", "languageId", "priority") DO UPDATE SET
  "translation" = EXCLUDED."translation",
  "partOfSpeechId" = EXCLUDED."partOfSpeechId";

-- Заменяем примеры: удаляем старые и вставляем новые.
-- Новые примеры помечаем sourceId = dm_... (для выборочного удаления при rollback)
DELETE FROM "WordExample"
WHERE "baseWordId" IN (
  SELECT "id" FROM "BaseWord"
  WHERE "word" IN ('accusing', 'authenticity', 'backpressure')
  AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')
);

-- Ensure sentence types exist
INSERT INTO "SentenceType" ("code", "displayName", "isNegative", "isQuestion") VALUES ('AFFIRMATIVE', 'affirmative', false, false)
ON CONFLICT ("code") DO NOTHING;
INSERT INTO "SentenceType" ("code", "displayName", "isNegative", "isQuestion") VALUES ('QUESTION', 'question', false, true)
ON CONFLICT ("code") DO NOTHING;
INSERT INTO "SentenceType" ("code", "displayName", "isNegative", "isQuestion") VALUES ('NEGATIVE', 'negative', true, false)
ON CONFLICT ("code") DO NOTHING;

INSERT INTO "WordExample" ("baseWordId", "pronounId", "example", "translation", "translationLanguageId", "sentenceTypeId", "sourceId") VALUES
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'accusing' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'I' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'I am accusing him of theft', 'Я обвиняю его в краже', (SELECT "id" FROM "Language" WHERE "code" = 'ru'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260729170032_deepl_en')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'accusing' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'I' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'I am accusing him of theft', 'Lo estoy acusando de robo', (SELECT "id" FROM "Language" WHERE "code" = 'es'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260729170032_deepl_en')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'accusing' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'you' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'Are you accusing me?', 'Ты меня обвиняешь?', (SELECT "id" FROM "Language" WHERE "code" = 'ru'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'QUESTION'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260729170032_deepl_en')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'accusing' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'you' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'Are you accusing me?', '¿Me estás acusando?', (SELECT "id" FROM "Language" WHERE "code" = 'es'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'QUESTION'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260729170032_deepl_en')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'accusing' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'he' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'He isn''t accusing anyone', 'Он никого не обвиняет', (SELECT "id" FROM "Language" WHERE "code" = 'ru'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'NEGATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260729170032_deepl_en')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'accusing' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'he' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'He isn''t accusing anyone', 'Él no está acusando a nadie', (SELECT "id" FROM "Language" WHERE "code" = 'es'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'NEGATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260729170032_deepl_en')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'accusing' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'we' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'We heard an accusing tone', 'Мы услышали обвиняющий тон', (SELECT "id" FROM "Language" WHERE "code" = 'ru'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260729170032_deepl_en')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'accusing' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'we' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'We heard an accusing tone', 'Escuchamos un tono acusador', (SELECT "id" FROM "Language" WHERE "code" = 'es'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260729170032_deepl_en')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'accusing' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'they' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'They were accusing her wrongly', 'Они несправедливо обвиняли её', (SELECT "id" FROM "Language" WHERE "code" = 'ru'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260729170032_deepl_en')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'accusing' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'they' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'They were accusing her wrongly', 'La estaban acusando injustamente', (SELECT "id" FROM "Language" WHERE "code" = 'es'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260729170032_deepl_en')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'authenticity' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'I' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'I value authenticity in my work.', 'Я ценю подлинность в своей работе.', (SELECT "id" FROM "Language" WHERE "code" = 'ru'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260729170032_deepl_en')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'authenticity' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'I' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'I value authenticity in my work.', 'Valoro la autenticidad en mi trabajo.', (SELECT "id" FROM "Language" WHERE "code" = 'es'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260729170032_deepl_en')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'authenticity' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'you' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'You showed real authenticity today.', 'Сегодня ты показал истинную подлинность.', (SELECT "id" FROM "Language" WHERE "code" = 'ru'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260729170032_deepl_en')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'authenticity' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'you' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'You showed real authenticity today.', 'Hoy mostraste autenticidad real.', (SELECT "id" FROM "Language" WHERE "code" = 'es'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260729170032_deepl_en')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'authenticity' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'he' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'Does he doubt the authenticity?', 'Он сомневается в подлинности?', (SELECT "id" FROM "Language" WHERE "code" = 'ru'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'QUESTION'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260729170032_deepl_en')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'authenticity' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'he' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'Does he doubt the authenticity?', '¿Él duda de la autenticidad?', (SELECT "id" FROM "Language" WHERE "code" = 'es'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'QUESTION'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260729170032_deepl_en')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'authenticity' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'we' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'We don''t accept false authenticity.', 'Мы не принимаем фальшивую подлинность.', (SELECT "id" FROM "Language" WHERE "code" = 'ru'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'NEGATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260729170032_deepl_en')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'authenticity' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'we' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'We don''t accept false authenticity.', 'No aceptamos una autenticidad falsa.', (SELECT "id" FROM "Language" WHERE "code" = 'es'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'NEGATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260729170032_deepl_en')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'authenticity' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'they' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'They questioned the authenticity of the document.', 'Они усомнились в подлинности документа.', (SELECT "id" FROM "Language" WHERE "code" = 'ru'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260729170032_deepl_en')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'authenticity' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'they' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'They questioned the authenticity of the document.', 'Cuestionaron la autenticidad del documento.', (SELECT "id" FROM "Language" WHERE "code" = 'es'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260729170032_deepl_en')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'backpressure' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'I' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'I measured the backpressure.', 'Я измерил обратное давление.', (SELECT "id" FROM "Language" WHERE "code" = 'ru'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260729170032_deepl_en')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'backpressure' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'I' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'I measured the backpressure.', 'Medí la contrapresión.', (SELECT "id" FROM "Language" WHERE "code" = 'es'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260729170032_deepl_en')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'backpressure' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'you' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'You caused backpressure in the system.', 'Ты вызвал обратное давление в системе.', (SELECT "id" FROM "Language" WHERE "code" = 'ru'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260729170032_deepl_en')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'backpressure' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'you' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'You caused backpressure in the system.', 'Provocaste contrapresión en el sistema.', (SELECT "id" FROM "Language" WHERE "code" = 'es'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260729170032_deepl_en')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'backpressure' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'he' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'Does he know about backpressure?', 'Он знает об обратном давлении?', (SELECT "id" FROM "Language" WHERE "code" = 'ru'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'QUESTION'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260729170032_deepl_en')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'backpressure' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'he' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'Does he know about backpressure?', '¿Él sabe qué es la contrapresión?', (SELECT "id" FROM "Language" WHERE "code" = 'es'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'QUESTION'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260729170032_deepl_en')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'backpressure' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'we' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'We don''t see any backpressure.', 'Мы не видим обратного давления.', (SELECT "id" FROM "Language" WHERE "code" = 'ru'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'NEGATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260729170032_deepl_en')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'backpressure' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'we' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'We don''t see any backpressure.', 'No vemos ninguna contrapresión.', (SELECT "id" FROM "Language" WHERE "code" = 'es'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'NEGATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260729170032_deepl_en')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'backpressure' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'they' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'They reduced the backpressure.', 'Они снизили обратное давление.', (SELECT "id" FROM "Language" WHERE "code" = 'ru'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260729170032_deepl_en')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'backpressure' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'they' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'They reduced the backpressure.', 'Redujeron la contrapresión.', (SELECT "id" FROM "Language" WHERE "code" = 'es'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260729170032_deepl_en'))
ON CONFLICT DO NOTHING;

DELETE FROM "GrammaticalExample"
WHERE "baseWordId" IN (
  SELECT "id" FROM "BaseWord"
  WHERE "word" IN ('accusing', 'authenticity', 'backpressure')
  AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')
);

-- Ensure tenses exist
INSERT INTO "Tense" ("name", "languageId") VALUES ('Present Simple', (SELECT "id" FROM "Language" WHERE "code" = 'en'))
ON CONFLICT ("name", "languageId") DO NOTHING;
INSERT INTO "Tense" ("name", "languageId") VALUES ('Past Simple', (SELECT "id" FROM "Language" WHERE "code" = 'en'))
ON CONFLICT ("name", "languageId") DO NOTHING;
INSERT INTO "Tense" ("name", "languageId") VALUES ('Future Simple', (SELECT "id" FROM "Language" WHERE "code" = 'en'))
ON CONFLICT ("name", "languageId") DO NOTHING;

-- Ensure pronouns exist
INSERT INTO "Pronoun" ("pronoun", "languageId") VALUES ('I', (SELECT "id" FROM "Language" WHERE "code" = 'en'))
ON CONFLICT ("pronoun", "languageId") DO NOTHING;
INSERT INTO "Pronoun" ("pronoun", "languageId") VALUES ('I', (SELECT "id" FROM "Language" WHERE "code" = 'en'))
ON CONFLICT ("pronoun", "languageId") DO NOTHING;
INSERT INTO "Pronoun" ("pronoun", "languageId") VALUES ('you', (SELECT "id" FROM "Language" WHERE "code" = 'en'))
ON CONFLICT ("pronoun", "languageId") DO NOTHING;
INSERT INTO "Pronoun" ("pronoun", "languageId") VALUES ('you', (SELECT "id" FROM "Language" WHERE "code" = 'en'))
ON CONFLICT ("pronoun", "languageId") DO NOTHING;
INSERT INTO "Pronoun" ("pronoun", "languageId") VALUES ('he', (SELECT "id" FROM "Language" WHERE "code" = 'en'))
ON CONFLICT ("pronoun", "languageId") DO NOTHING;
INSERT INTO "Pronoun" ("pronoun", "languageId") VALUES ('he', (SELECT "id" FROM "Language" WHERE "code" = 'en'))
ON CONFLICT ("pronoun", "languageId") DO NOTHING;
INSERT INTO "Pronoun" ("pronoun", "languageId") VALUES ('we', (SELECT "id" FROM "Language" WHERE "code" = 'en'))
ON CONFLICT ("pronoun", "languageId") DO NOTHING;
INSERT INTO "Pronoun" ("pronoun", "languageId") VALUES ('we', (SELECT "id" FROM "Language" WHERE "code" = 'en'))
ON CONFLICT ("pronoun", "languageId") DO NOTHING;
INSERT INTO "Pronoun" ("pronoun", "languageId") VALUES ('you', (SELECT "id" FROM "Language" WHERE "code" = 'en'))
ON CONFLICT ("pronoun", "languageId") DO NOTHING;
INSERT INTO "Pronoun" ("pronoun", "languageId") VALUES ('you', (SELECT "id" FROM "Language" WHERE "code" = 'en'))
ON CONFLICT ("pronoun", "languageId") DO NOTHING;
INSERT INTO "Pronoun" ("pronoun", "languageId") VALUES ('they', (SELECT "id" FROM "Language" WHERE "code" = 'en'))
ON CONFLICT ("pronoun", "languageId") DO NOTHING;
INSERT INTO "Pronoun" ("pronoun", "languageId") VALUES ('they', (SELECT "id" FROM "Language" WHERE "code" = 'en'))
ON CONFLICT ("pronoun", "languageId") DO NOTHING;
INSERT INTO "Pronoun" ("pronoun", "languageId") VALUES ('I', (SELECT "id" FROM "Language" WHERE "code" = 'en'))
ON CONFLICT ("pronoun", "languageId") DO NOTHING;
INSERT INTO "Pronoun" ("pronoun", "languageId") VALUES ('I', (SELECT "id" FROM "Language" WHERE "code" = 'en'))
ON CONFLICT ("pronoun", "languageId") DO NOTHING;
INSERT INTO "Pronoun" ("pronoun", "languageId") VALUES ('you', (SELECT "id" FROM "Language" WHERE "code" = 'en'))
ON CONFLICT ("pronoun", "languageId") DO NOTHING;
INSERT INTO "Pronoun" ("pronoun", "languageId") VALUES ('you', (SELECT "id" FROM "Language" WHERE "code" = 'en'))
ON CONFLICT ("pronoun", "languageId") DO NOTHING;
INSERT INTO "Pronoun" ("pronoun", "languageId") VALUES ('he', (SELECT "id" FROM "Language" WHERE "code" = 'en'))
ON CONFLICT ("pronoun", "languageId") DO NOTHING;
INSERT INTO "Pronoun" ("pronoun", "languageId") VALUES ('he', (SELECT "id" FROM "Language" WHERE "code" = 'en'))
ON CONFLICT ("pronoun", "languageId") DO NOTHING;
INSERT INTO "Pronoun" ("pronoun", "languageId") VALUES ('we', (SELECT "id" FROM "Language" WHERE "code" = 'en'))
ON CONFLICT ("pronoun", "languageId") DO NOTHING;
INSERT INTO "Pronoun" ("pronoun", "languageId") VALUES ('we', (SELECT "id" FROM "Language" WHERE "code" = 'en'))
ON CONFLICT ("pronoun", "languageId") DO NOTHING;
INSERT INTO "Pronoun" ("pronoun", "languageId") VALUES ('you', (SELECT "id" FROM "Language" WHERE "code" = 'en'))
ON CONFLICT ("pronoun", "languageId") DO NOTHING;
INSERT INTO "Pronoun" ("pronoun", "languageId") VALUES ('you', (SELECT "id" FROM "Language" WHERE "code" = 'en'))
ON CONFLICT ("pronoun", "languageId") DO NOTHING;
INSERT INTO "Pronoun" ("pronoun", "languageId") VALUES ('they', (SELECT "id" FROM "Language" WHERE "code" = 'en'))
ON CONFLICT ("pronoun", "languageId") DO NOTHING;
INSERT INTO "Pronoun" ("pronoun", "languageId") VALUES ('they', (SELECT "id" FROM "Language" WHERE "code" = 'en'))
ON CONFLICT ("pronoun", "languageId") DO NOTHING;
INSERT INTO "Pronoun" ("pronoun", "languageId") VALUES ('I', (SELECT "id" FROM "Language" WHERE "code" = 'en'))
ON CONFLICT ("pronoun", "languageId") DO NOTHING;
INSERT INTO "Pronoun" ("pronoun", "languageId") VALUES ('I', (SELECT "id" FROM "Language" WHERE "code" = 'en'))
ON CONFLICT ("pronoun", "languageId") DO NOTHING;
INSERT INTO "Pronoun" ("pronoun", "languageId") VALUES ('you', (SELECT "id" FROM "Language" WHERE "code" = 'en'))
ON CONFLICT ("pronoun", "languageId") DO NOTHING;
INSERT INTO "Pronoun" ("pronoun", "languageId") VALUES ('you', (SELECT "id" FROM "Language" WHERE "code" = 'en'))
ON CONFLICT ("pronoun", "languageId") DO NOTHING;
INSERT INTO "Pronoun" ("pronoun", "languageId") VALUES ('he', (SELECT "id" FROM "Language" WHERE "code" = 'en'))
ON CONFLICT ("pronoun", "languageId") DO NOTHING;
INSERT INTO "Pronoun" ("pronoun", "languageId") VALUES ('he', (SELECT "id" FROM "Language" WHERE "code" = 'en'))
ON CONFLICT ("pronoun", "languageId") DO NOTHING;
INSERT INTO "Pronoun" ("pronoun", "languageId") VALUES ('we', (SELECT "id" FROM "Language" WHERE "code" = 'en'))
ON CONFLICT ("pronoun", "languageId") DO NOTHING;
INSERT INTO "Pronoun" ("pronoun", "languageId") VALUES ('we', (SELECT "id" FROM "Language" WHERE "code" = 'en'))
ON CONFLICT ("pronoun", "languageId") DO NOTHING;
INSERT INTO "Pronoun" ("pronoun", "languageId") VALUES ('you', (SELECT "id" FROM "Language" WHERE "code" = 'en'))
ON CONFLICT ("pronoun", "languageId") DO NOTHING;
INSERT INTO "Pronoun" ("pronoun", "languageId") VALUES ('you', (SELECT "id" FROM "Language" WHERE "code" = 'en'))
ON CONFLICT ("pronoun", "languageId") DO NOTHING;
INSERT INTO "Pronoun" ("pronoun", "languageId") VALUES ('they', (SELECT "id" FROM "Language" WHERE "code" = 'en'))
ON CONFLICT ("pronoun", "languageId") DO NOTHING;
INSERT INTO "Pronoun" ("pronoun", "languageId") VALUES ('they', (SELECT "id" FROM "Language" WHERE "code" = 'en'))
ON CONFLICT ("pronoun", "languageId") DO NOTHING;

INSERT INTO "GrammaticalExample" ("baseWordId", "tenseId", "pronounId", "example", "translation", "translationLanguageId", "sentenceTypeId", "sourceId") VALUES
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'accusing' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Tense" WHERE "name" = 'Present Simple' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'I' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'I am accusing her', 'Я обвиняю её', (SELECT "id" FROM "Language" WHERE "code" = 'ru'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260729170032_deepl_en')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'accusing' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Tense" WHERE "name" = 'Present Simple' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'I' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'I am accusing her', 'La estoy acusando', (SELECT "id" FROM "Language" WHERE "code" = 'es'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260729170032_deepl_en')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'accusing' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Tense" WHERE "name" = 'Present Simple' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'you' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'You are accusing him', 'Ты обвиняешь его', (SELECT "id" FROM "Language" WHERE "code" = 'ru'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260729170032_deepl_en')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'accusing' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Tense" WHERE "name" = 'Present Simple' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'you' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'You are accusing him', 'Lo estás acusando', (SELECT "id" FROM "Language" WHERE "code" = 'es'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260729170032_deepl_en')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'accusing' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Tense" WHERE "name" = 'Present Simple' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'he' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'He is accusing them', 'Он обвиняет их', (SELECT "id" FROM "Language" WHERE "code" = 'ru'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260729170032_deepl_en')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'accusing' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Tense" WHERE "name" = 'Present Simple' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'he' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'He is accusing them', 'Los está acusando', (SELECT "id" FROM "Language" WHERE "code" = 'es'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260729170032_deepl_en')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'accusing' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Tense" WHERE "name" = 'Present Simple' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'we' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'Are we accusing him?', 'Мы его обвиняем?', (SELECT "id" FROM "Language" WHERE "code" = 'ru'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'QUESTION'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260729170032_deepl_en')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'accusing' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Tense" WHERE "name" = 'Present Simple' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'we' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'Are we accusing him?', '¿Lo estamos acusando?', (SELECT "id" FROM "Language" WHERE "code" = 'es'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'QUESTION'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260729170032_deepl_en')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'accusing' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Tense" WHERE "name" = 'Present Simple' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'you' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'You are accusing me', 'Вы меня обвиняете', (SELECT "id" FROM "Language" WHERE "code" = 'ru'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260729170032_deepl_en')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'accusing' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Tense" WHERE "name" = 'Present Simple' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'you' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'You are accusing me', 'Me estáis acusando', (SELECT "id" FROM "Language" WHERE "code" = 'es'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260729170032_deepl_en')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'accusing' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Tense" WHERE "name" = 'Present Simple' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'they' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'They aren''t accusing us', 'Они нас не обвиняют', (SELECT "id" FROM "Language" WHERE "code" = 'ru'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'NEGATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260729170032_deepl_en')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'accusing' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Tense" WHERE "name" = 'Present Simple' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'they' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'They aren''t accusing us', 'No nos están acusando', (SELECT "id" FROM "Language" WHERE "code" = 'es'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'NEGATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260729170032_deepl_en')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'accusing' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Tense" WHERE "name" = 'Past Simple' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'I' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'I was accusing her', 'Я обвинял её', (SELECT "id" FROM "Language" WHERE "code" = 'ru'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260729170032_deepl_en')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'accusing' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Tense" WHERE "name" = 'Past Simple' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'I' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'I was accusing her', 'La estaba acusando', (SELECT "id" FROM "Language" WHERE "code" = 'es'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260729170032_deepl_en')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'accusing' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Tense" WHERE "name" = 'Past Simple' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'you' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'You were accusing him', 'Ты обвинял его', (SELECT "id" FROM "Language" WHERE "code" = 'ru'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260729170032_deepl_en')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'accusing' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Tense" WHERE "name" = 'Past Simple' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'you' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'You were accusing him', 'Lo estabas acusando', (SELECT "id" FROM "Language" WHERE "code" = 'es'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260729170032_deepl_en')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'accusing' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Tense" WHERE "name" = 'Past Simple' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'he' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'He wasn''t accusing them', 'Он их не обвинял', (SELECT "id" FROM "Language" WHERE "code" = 'ru'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'NEGATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260729170032_deepl_en')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'accusing' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Tense" WHERE "name" = 'Past Simple' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'he' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'He wasn''t accusing them', 'No los estaba acusando', (SELECT "id" FROM "Language" WHERE "code" = 'es'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'NEGATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260729170032_deepl_en')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'accusing' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Tense" WHERE "name" = 'Past Simple' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'we' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'We were accusing no one', 'Мы никого не обвиняли', (SELECT "id" FROM "Language" WHERE "code" = 'ru'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260729170032_deepl_en')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'accusing' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Tense" WHERE "name" = 'Past Simple' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'we' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'We were accusing no one', 'No estábamos acusando a nadie', (SELECT "id" FROM "Language" WHERE "code" = 'es'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260729170032_deepl_en')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'accusing' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Tense" WHERE "name" = 'Past Simple' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'you' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'You were accusing me', 'Вы меня обвиняли', (SELECT "id" FROM "Language" WHERE "code" = 'ru'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260729170032_deepl_en')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'accusing' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Tense" WHERE "name" = 'Past Simple' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'you' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'You were accusing me', 'Me estabais acusando', (SELECT "id" FROM "Language" WHERE "code" = 'es'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260729170032_deepl_en')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'accusing' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Tense" WHERE "name" = 'Past Simple' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'they' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'Were they accusing us?', 'Они нас обвиняли?', (SELECT "id" FROM "Language" WHERE "code" = 'ru'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'QUESTION'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260729170032_deepl_en')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'accusing' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Tense" WHERE "name" = 'Past Simple' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'they' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'Were they accusing us?', '¿Nos estaban acusando?', (SELECT "id" FROM "Language" WHERE "code" = 'es'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'QUESTION'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260729170032_deepl_en')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'accusing' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Tense" WHERE "name" = 'Future Simple' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'I' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'I will be accusing her', 'Я буду обвинять её', (SELECT "id" FROM "Language" WHERE "code" = 'ru'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260729170032_deepl_en')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'accusing' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Tense" WHERE "name" = 'Future Simple' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'I' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'I will be accusing her', 'La estaré acusando', (SELECT "id" FROM "Language" WHERE "code" = 'es'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260729170032_deepl_en')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'accusing' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Tense" WHERE "name" = 'Future Simple' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'you' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'You will be accusing him', 'Ты будешь обвинять его', (SELECT "id" FROM "Language" WHERE "code" = 'ru'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260729170032_deepl_en')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'accusing' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Tense" WHERE "name" = 'Future Simple' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'you' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'You will be accusing him', 'Lo estarás acusando', (SELECT "id" FROM "Language" WHERE "code" = 'es'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260729170032_deepl_en')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'accusing' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Tense" WHERE "name" = 'Future Simple' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'he' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'He will be accusing them', 'Он будет обвинять их', (SELECT "id" FROM "Language" WHERE "code" = 'ru'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260729170032_deepl_en')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'accusing' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Tense" WHERE "name" = 'Future Simple' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'he' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'He will be accusing them', 'Los estará acusando', (SELECT "id" FROM "Language" WHERE "code" = 'es'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260729170032_deepl_en')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'accusing' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Tense" WHERE "name" = 'Future Simple' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'we' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'We won''t be accusing anyone', 'Мы никого не будем обвинять', (SELECT "id" FROM "Language" WHERE "code" = 'ru'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'NEGATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260729170032_deepl_en')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'accusing' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Tense" WHERE "name" = 'Future Simple' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'we' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'We won''t be accusing anyone', 'No estaremos acusando a nadie', (SELECT "id" FROM "Language" WHERE "code" = 'es'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'NEGATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260729170032_deepl_en')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'accusing' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Tense" WHERE "name" = 'Future Simple' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'you' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'You will be accusing me', 'Вы будете меня обвинять', (SELECT "id" FROM "Language" WHERE "code" = 'ru'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260729170032_deepl_en')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'accusing' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Tense" WHERE "name" = 'Future Simple' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'you' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'You will be accusing me', 'Me estaréis acusando', (SELECT "id" FROM "Language" WHERE "code" = 'es'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'AFFIRMATIVE'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260729170032_deepl_en')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'accusing' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Tense" WHERE "name" = 'Future Simple' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'they' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'Will they be accusing us?', 'Они будут нас обвинять?', (SELECT "id" FROM "Language" WHERE "code" = 'ru'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'QUESTION'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260729170032_deepl_en')),
  ((SELECT "id" FROM "BaseWord" WHERE "word" = 'accusing' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Tense" WHERE "name" = 'Future Simple' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), (SELECT "id" FROM "Pronoun" WHERE "pronoun" = 'they' AND "languageId" = (SELECT "id" FROM "Language" WHERE "code" = 'en')), 'Will they be accusing us?', '¿Nos estarán acusando?', (SELECT "id" FROM "Language" WHERE "code" = 'es'), (SELECT "id" FROM "SentenceType" WHERE "code" = 'QUESTION'), (SELECT "id" FROM "WordSource" WHERE "code" = 'dm_20260729170032_deepl_en'))
ON CONFLICT DO NOTHING;

-- Запись о применении, времени, checksum и gitSha выполняется apply-скриптом параметрами после успешного выполнения

SELECT pg_advisory_unlock(hashtext('data_migrations_global_lock'));
COMMIT;